apiVersion: v1
kind: Namespace
metadata:
  name: controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reload
  namespace: controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: reload-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: reload
    namespace: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reload
  namespace: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reload
  template:
    metadata:
      labels:
        app: reload
    spec:
      serviceAccount: reload
      containers:
      - name: reload
        image: l453595892/reload:latest
        imagePullPolicy: IfNotPresent
